# Site
repository: andywoodruff6.github.io
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Andrew Woodruff
title: Project Manager
email: andywoodruff6@gmail.com
# email_title: Email (Email title override)
# phone: Your phone number (optional)
# phone_title: Phone (Phone title override)
website: https://andywoodruff6.github.io/
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: WoodruffAndy
github_username:  andywoodruff6
substack_username: andywoodruff6
#stackoverflow_username: "00000001"
#dribbble_username: jekyll
#facebook_username: jekyll
#flickr_username: jekyll
#instagram_username: jekyll
#linkedin_username: jekyll
#xing_username: jekyll
#pinterest_username: jekyll
#youtube_username: jekyll
#orcid_username: 0000-0000-0000-0000
#googlescholar_username: D847cGsAAAAJ

# Additional icon links
additional_links:
- title: LinkedIn
  icon: fab fa-linkedin
  url: https://www.linkedin.com/in/andrew-woodruff-72b70075/
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/profile_pic.jpg
about_content: | # this will include new lines to allow paragraphs
  # Driven towards the bleeding edge by an obsession for efficiency and innovation.

  I have 1 year experience as a product owner and 4 years experience as a project manager. In that time delivered 6 products to market. I am PMP Certified and have a Bachelors in Mechanical Engineering.

  In my free time I enjoy riding and racing my bicycle and playing board games.

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        border: weak
        title: Open Commercial Media Ecosystem
        link: https://ocmeco.org/
        link_text: https://ocmeco.org/
        quote: >
          Short overview of the project (optional)
        description: | # this will include new lines to allow paragraphs
          testing info

      - layout: left
        border: weak
        title: Trust over IP
        link: https://trustoverip.org/
        link_text: https://trustoverip.org/
        # quote: >
        #   Short overview of the project (optional)
        description: | # this will include new lines to allow paragraphs
          Trust over IP is a project that is working to create a new standard for digital identity. The project is backed by the Linux Foundation and has over 100 members. I am a member of the technology Stack Working Group and a co-chair of the Human Experience Working Group.
  - title: Experience
    layout: list
    content:
      - layout: left
        border: weak
        title: Alliant Energy
        sub_title: Strategic Project Manager
        caption: January 2023 - present
        # link: https://www.alliantenergy.com/
        quote: >
          Alliant Energy Corporation provides regulated energy service to 995,000 electric and 425,000 natural gas retail customers across Iowa and Wisconsin.
        description: | # this will include new lines to allow paragraphs
          - Coordinated the strategic deployment of IBM Maximo to Azure Cloud with a cross-functional team of over 200 employees, overseeing 6 sub teams, resulting in an operational savings of $1,000,000 per year.
          - Executed risk management strategies through Jira to reduce and resolve issues and blockers, decreasing budget overruns by $570,000.
          - Utilized strong interpersonal skills to build relationships with team members and management in a matrix team structure, facilitating smoother communication channels and reducing project delays.
          - Assigned actionable tasks to owners in every meeting and conducted team wide and project wide retrospectives to drive continious improvement saving 3 weeks during our Bundle 2 release. 
      - layout: left
        border: weak
        title: Foundry Digital
        sub_title: Product Owner
        caption: 2022-2022
        # link: Link to company (optional)
        quote: >
          Foundry Digital is the leading Bitcoin mining pool in North America, backed by Digital Currency Group.
        description: | # this will include new lines to allow paragraphs
          - Utilized market research data to create a comprehensive go-to-market strategy including key product requirements definitions and pricing recommendations esulting in the successful launch of 10 new features and enhancements.
          - Established a product roadmap and implementation strategy of new features on the OTC brokerage marketplace, resulting in a 30% increase in user engagement metrics.
          - Facilitated sprint planning, daily stand-ups, and retrospectives in a rapidly changing blockchain industry with a cross-functional team of 6 members, resulting in a 60% increase in team productivity.
          - Implemented Confluence as a centralized knowledge hub for cross-functional teams to understand our product strategy, leading to a significant reduction in time spent searching for information.
          - Utilized data analytics to identify key areas of improvement in product messaging, leading to a 20% increase in customer engagement levels.
      - layout: left
        border: weak
        title: Upstate Interactive
        sub_title: Smart Contract Engineer
        caption: 2021 - 2022
        # link: Link to company (optional)
        quote: >
          Upstate Interactive is a contract software development company that specializes in building Ethereum smart contracts and websites for businesses.
        description: | # this will include new lines to allow paragraphs
          - Coordinated weekly meetings with clients and developers to prioritize feature development, resulting in a 100% on- time delivery rate of new smart contract features.
          - Successfully managed and prioritized tasks for 3 software development projects concurrently, using GitHub Projects. Tightening the feedback loop allowed for better decision-making.
          - Led the redesign of the product interface based on user feedback and A/B testing data, resulting in a 30% increase in user engagement metrics.
      - layout: left
        border: weak
        title: Regal Beloit
        sub_title: Application Engineer
        caption: 2018 - 2021
        # link: Link to company (optional)
        quote: >
          Regal Beloit Corporation is a leading manufacturer of electric motors serving markets throughout the world.
        description: | # this will include new lines to allow paragraphs
          - Executed detailed project planning to oversee the completion of 10 customer-driven initiatives.
          - Lead the development of four new blower products earning the company $2,000,000 per year.
          - Utilized advanced problem-solving techniques to streamline communication and collaboration between departments, resulting in a 15% decrease in production defects.
          - Utilized statistical modeling techniques and problem-solving skills to analyze the impact of reducing SKU count by 50%, resulting in a projected cost savings of $1.5 million within the first year.
  - title: Certifications
    layout: list
    content:
      - layout: left
        title: Project Management Professional
        # sub_title: PMP
        caption: Nov. 2023
        # quote: >
        #   Short institution or course description (optional)
        description: | # this will include new lines to allow paragraphs
          The PMP is the gold standard of project management certification. Recognized and demanded by organizations worldwide, the PMP validates your competence to perform in the role of a project manager, leading and directing projects and teams.
      - layout: left
        title: Google AI Essentials
        # sub_title: PMP
        caption: June 2024
        # quote: >
        #   Short institution or course description (optional)
        description: | # this will include new lines to allow paragraphs
          Google AI Essentials is a self-paced course designed to help people across roles and industries get essential AI skills to boost their productivity, zero experience required. The course is taught by AI experts at Google who are working to make the technology helpful for everyone.
      - layout: left
        title: Six Sigma Green Belt
        caption: Aug. 2021
        description: | # this will include new lines to allow paragraphs
          Six Sigma Green Belt Certification is a globally recognized certification that equips the candidates and professionals with numerous measures, skills, and controls that are essential for handling and ensuring a smooth flow of processes in organizations.
      - layout: left
        title: Atala Prism 101, 102, and 103
        caption: Aug. 2022
        description: | # this will include new lines to allow paragraphs
          Atala PRISM is a decentralized identity solution that allows users to create and manage their digital identities. Atala is secured by the Cardano blockchain and allows for identity interactions with smart contracts. 101 provides The foundational principles and concepts of self-sovereign identity (SSI). 102 covers building applications with Atala PRISM. 103 covers a foundation in designing human-centric solutions for decentralized ecosystems. 
  - title: Education
    layout: list
    content:
      - layout: center
        title: Project Management Professional (PMP)
        description: 
          I earned my PMP certification in under 3 weeks while working full time leveraging my Ultralearning framework and Obsidian. ![PMP knowledge Graph](images/PMP-Knowledge-Graph.png)
      - layout: center
        title: Any Time, Any Location
        description: We receive knowledge that we want to remember from many locations at any time of the day. Using Obsidian I have access to all of it when ever and where ever. I can capture and distill information with unparalleled efficiency ![Info Processing](images/Info-Processing.png)
      - layout: top-left
        title: Ohio Northern University
        sub_title: Bachelors of Science in Mechanical Engineering
        # quote: >
        #   Short institution or course description (optional)
        description: | # this will include new lines to allow paragraphs
          At Ohio Northern I was involved in Human Powered Vehicle and the American Society of Mechanical Engineers. Course work was heavily focused on collaboration, group projects and presentations.
  - title: About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      ## Beyond the Product
      I've always been driven to achieve more with less. From a young age, I co-founded my first company at 16, which still runs today, supporting STEM initiatives in my hometown. This, combined with my degree in Mechanical Engineering set the foundation for being action oriented and a fast paced problem solver. ![My RoadBike](images/My-roadbike.jpg)

      ## Innovators Robotics
      My journey to the bleeding edge began freshman year of high school when I started a robotics team with my friends. Four years, three design awards, and one non profit business later my trajectory was set. The business is still in operation today and has given thousands of kids a chance to learn about STEM.

      ## My Inspirations and Interests
      When I'm not building new products or learning about new technology you can find me riding my bike, or hiking. When I get home, tired from my outdoor activities, I enjoy playing board games and video games with my friends and family. My favorite board game is Scythe and my favorite video game series is Borderlands. ![Pikes Peak](images/Pikes-peak.jpg)


# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
