# Site
repository: andywoodruff6.github.io
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Andrew Woodruff
title: Project Manager
email: andywoodruff6@gmail.com
# email_title: Email (Email title override)
# phone: Your phone number (optional)
# phone_title: Phone (Phone title override)
website: https://andywoodruff6.github.io/
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: WoodruffAndy
github_username:  andywoodruff6
substack_username: andywoodruff6
#stackoverflow_username: "00000001"
#dribbble_username: jekyll
#facebook_username: jekyll
#flickr_username: jekyll
#instagram_username: jekyll
#linkedin_username: jekyll
#xing_username: jekyll
#pinterest_username: jekyll
#youtube_username: jekyll
#orcid_username: 0000-0000-0000-0000
#googlescholar_username: D847cGsAAAAJ

# Additional icon links
additional_links:
# - title: Link name
#   icon: Font Awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/profile_pic.jpg
about_content: | # this will include new lines to allow paragraphs
  ## A project manager who can code.
  My technical background gives me the ability to understand the customer and the technical team.

  I have 1 year experience as a product owner and 4 years experience as a project manager. In that time delivered 6 products to market. I am PMP Certified and have a Bachelors in Mechanical Engineering.

  In my free time I enjoy riding and racing my bicycle and playing board games.

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: Project name
        link: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        link_text: Link Text
        additional_links:
          - title:  Github page for project (eg. sproogen/modern-resume-theme)
            icon: fab fa-github
            url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
          - title:  Github page for project (eg. sproogen/modern-resume-theme)
            icon: fab fa-github
            url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        quote: >
          Short overview of the project (optional)
        description: | # this will include new lines to allow paragraphs
          Description about the work on/with the project
      - layout: left
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: Project name
        link: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        link_text: Link Text
        additional_links:
          - title:  Github page for project (eg. sproogen/modern-resume-theme)
            icon: fab fa-github
            url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
          - title:  Github page for project (eg. sproogen/modern-resume-theme)
            icon: fab fa-github
            url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        quote: >
          Short overview of the project (optional)
        description: | # this will include new lines to allow paragraphs
          Description about the work on/with the project
  - title: Experience
    layout: list
    content:
      - layout: left
        title: Alliant Energy
        sub_title: Strategic Project Manager
        caption: January 2023 - present
        link: https://www.alliantenergy.com/
        quote: >
          Alliant Energy Corporation provides regulated energy service to 995,000 electric and 425,000 natural gas retail customers across Iowa and Wisconsin.
        description: | # this will include new lines to allow paragraphs
          - Worked on large projects critical to modernizing the company.
          - Deploying IBM Maximo with a team of 200+ people
          - Managed 6 different sub teams.  
      - layout: left
        title: Foundry Digital
        sub_title: Product Owner
        caption: 2022-2022
        # link: Link to company (optional)
        quote: >
          Foundry Digital is the leading Bitcoin mining pool in North America, backed by Digital Currency Group.
        description: | # this will include new lines to allow paragraphs
          - Lead a Competitive and Market analysis for a potential new product line
          - Lead a team of developers building out an OTC brokerage marketplace
          - Lead scrum ceremonies and delivered monthly road map presentations
          - Used productivity tools such as JIRA, GitLab, Confluence, and Miro
          - Lead a new project initiative focused on mining pool profitability using AWS
      - layout: left
        title: Upstate Interactive
        sub_title: Smart Contract Engineer
        caption: 2021 - 2022
        # link: Link to company (optional)
        quote: >
          Upstate Interactive is a contract software development company that specializes in building Ethereum smart contracts and websites for businesses.
        description: | # this will include new lines to allow paragraphs
          - Developed Smart Contracts in Solidity, utilizing Hardhat and Node.Js
          - Knowledgeable on the underlying technology of Bitcoin, Ethereum, and Cardano
          - Worked with Clients and Senior Devs to build advanced solutions
          - Used Notion and GitHub Projects to manage project workflow 
      - layout: left
        title: Regal Beloit
        sub_title: Application Engineer
        caption: 2018 - 2021
        # link: Link to company (optional)
        quote: >
          Regal Beloit Corporation is a leading manufacturer of electric motors serving markets throughout the world.
        description: | # this will include new lines to allow paragraphs
          - Lead customer driven projects, ensuring scope, timeline and budget were met
          - Lead New Product Development for four new blower products
          - Applied critical thinking to find the best solutions to complex multi-department problems
          - Compiled, evaluated, and presented test data to internal and external stakeholders
  - title: Certifications
    layout: list
    content:
      - layout: left
        title: Project Management Professional
        # sub_title: PMP
        caption: Nov. 2023
        # quote: >
        #   Short institution or course description (optional)
        description: | # this will include new lines to allow paragraphs
          The PMP is the gold standard of project management certification. Recognized and demanded by organizations worldwide, the PMP validates your competence to perform in the role of a project manager, leading and directing projects and teams.
      - layout: left
        title: Six Sigma Green Belt
        caption: Aug. 2021
        description: | # this will include new lines to allow paragraphs
          Six Sigma Green Belt Certification is a globally recognized certification that equips the candidates and professionals with numerous measures, skills, and controls that are essential for handling and ensuring a smooth flow of processes in organizations.
  - title: Education
    layout: list
    content:
      - layout: top-right
        title: Ohio Northern University
        sub_title: Bachelors of Science in Mechanical Engineering
        caption: 2012 - 2016
        # quote: >
        #   Short institution or course description (optional)
        description: | # this will include new lines to allow paragraphs
          At Ohio Northern I was involved in Human Powered Vehicle and the American Society of Mechanical Engineers. Course work was heavily focused on collaboration, group projects and presentations.
  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      ## Interests
      - Cycling (road and cyclocross)
      - Board games
      - Pickleball
      - Factory Building Games

      ## Leadership Experience
      - Coach and Board Member of Team Dayton Cycling Club (3 years)
      - Coach of Fair Valley Swim Team (6 years)

# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
